sudo: false
language: cpp

compiler: gcc 

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8

before_install:
  - cd Code
  - echo $LANG
  - echo $LC_ALL
  - export CXX="g++-4.8"

script: make -j2