######################################################################
# Automatically generated by qmake (3.0) Thu May 12 15:46:26 2016
######################################################################

TEMPLATE = app
TARGET = Code
INCLUDEPATH += .

# Input
HEADERS += typedefs.h
SOURCES += main.cpp Algorithm1/algorithm1.cpp

DISTFILES += \
    uncrustify.cfg
