######################################################################
# Automatically generated by qmake (3.0) Thu May 12 15:46:26 2016
######################################################################

TEMPLATE = app
TARGET = Code
INCLUDEPATH += .
CONFIG += c++11

# Input

SOURCES += main.cpp
QMAKE_CXXFLAGS += -std=c++11

DISTFILES += \
    uncrustify.cfg \
    Makefile \
    .config
